"""Specialized agents package."""
from .arbitrage_agent import ArbitrageAgent
from .breakout_agent import BreakoutAgent
from .communication_services_agent import CommunicationServicesAgent
from .consumer_discretionary_agent import ConsumerDiscretionaryAgent
from .consumer_staples_agent import ConsumerStaplesAgent
from .crypto_agent import CryptoAgent
from .dividend_agent import DividendAgent
from .earnings_agent import EarningsAgent
from .energy_agent import EnergyAgent
from .financials_agent import FinancialsAgent
from .forex_agent import ForexAgent
from .futures_agent import FuturesAgent
from .growth_agent import GrowthAgent
from .healthcare_agent import HealthcareAgent
from .industrials_agent import IndustrialsAgent
from .insider_agent import InsiderAgent
from .long_short_agent import LongShortAgent
from .macro_agent import MacroAgent
from .materials_agent import MaterialsAgent
from .mean_reversion_agent import MeanReversionAgent
from .options_agent import OptionsAgent
from .pairs_trading_agent import PairsTradingAgent
from .real_estate_agent import RealEstateAgent
from .rotation_agent import RotationAgent
from .sector_agent import SectorAgent
from .short_agent import ShortAgent
from .strategy_agent import StrategyAgent
from .tech_agent import TechAgent
from .trend_following_agent import TrendFollowingAgent
from .utilities_agent import UtilitiesAgent
from .volatility_agent import VolatilityAgent
__all__ = [name for name in globals() if name.endswith('Agent')]
